% dhTransform.m
% 2020-10-2
% A. Cornelius

% This function generates the DH transformation matrix for a given set of
% a, alpha, d, theta values

function transformation = dhTransform(a, alpha, d, theta)
    transformation = [...
        cos(theta)  (-sin(theta)*cos(alpha))    sin(theta)*sin(alpha)   a*cos(theta);...
        sin(theta)  cos(theta)*cos(alpha)       -cos(theta)*sin(alpha)  a*sin(theta); ...
        0           sin(alpha)                  cos(alpha)              d;...
        0           0                           0                       1;...
        ];
end
