% requiredWristTransformation.m
% 2020-10-2
% A. Cornelius

% This function calculates the rotation transformation that is required to 
% go from a given position/orientation matrix (generated by forward
% kinematics of the first three axes of the robot) to the desired wrist
% orientation

% Inputs:
% forwardKinematicMatrix: the output of the forward kinematics for the
% first three joints. 4x4 position/rotation matrix (though only the
% rotation section is used.
% desiredOrientation: a 4x4 position/rotation matrix reflecting the desired
% position and orientation coming out of the wrist joint. Only the rotation
% section is used, since the pure wrist does not generate any translation

% wristRotation: a 4x4 rotation matrix reflecting the desired
% transformation for the spherical wrist

function wristRotation = requiredWristTransformation(forwardKinematicMatrix, desiredOrientation)
    wristRotation = [forwardKinematicMatrix(1:3, 1:3)' * desiredOrientation(1:3, 1:3), [0 0 0]'; [0 0 0 1]];
end